import type { Metadata } from "next";
import { Geist_Mono, Hedvig_Letters_Serif } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";

const hedvigLettersSerif = Hedvig_Letters_Serif({
  variable: "--font-hedvig-letters-serif",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Keystone",
  description: "Generated by create next app",
  icons: {
    icon: "/keystone-background.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hedvigLettersSerif.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          dynamic
          appearance={{ theme: shadcn }}
          signInUrl="/auth/sign-in"
          signUpUrl="/auth/sign-up"
        >
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
